### ISSUE TITLE
local script not working

### ISSUE THREAD

**Issue by dahshury** [grassick/whisperer#1]
![image](https://github.com/grassick/whisperer/assets/83991104/4fef4f4e-7204-468e-bff4-ef77c21a7a3f)
Running the local script then holding right ctrl keeps printing recording started many times when holding the ctrl key.
after that, it prints segmentation fault in the console. Never managed to get it it working. Tried not holding but just pressing, no luck.

**Comment by grassick** [comment]
Very strange! What operating system is this in? I looks like it's getting multiple onpress calls for a single keypress.

**Comment by dahshury** [comment]
It's windows 11. I'm a new programmer myself, but I think the code has problems. I fixed the repetition by adding if not recording in:

```
def on_press(key):
    global recording, stream, audio_data, translate

    if key == record_key:
      if not recording:
        
        recording = True
        translate = False
        print("Recording started...")
        audio_data = []

```

but couldn't fix the segmentation issue. It happens even outside the program, I tried to make a code that just takes the audio from my microphone and puts it into a file and it didn't work.

**Comment by Gerkinfeltser** [comment]
Yep, was having this same issue but @dahshury's fix did the trick (for that issue at least)! :D

**Comment by grassick** [comment]
Thanks for the feedback! It's now fixed.
