### ISSUE TITLE
Script Crash on Prolonged Key Press in "on_pressed" Function

### ISSUE THREAD

**Issue by Gerkinfeltser** [grassick/whisperer#2]
Hello!

I've encountered an issue when running the `whisperer.py` script. When I hold down a key that triggers the `on_pressed` function for more than 2 seconds, the script crashes. This results in a window popping up with two options: 1) Close the program, or 2) Debug the program. When I put option 2, I get another error message concerning VS & JIT debugging. Unfortunately, I'm not familiar with the Visual Studio Just-In-Time debugger and I don't have Visual Studio installed, only VSCode. Therefore, I'm unable to perform any debugging to provide more detailed information.

### Steps to Reproduce
1. Run `whisperer.py`.
2. Hold down a key linked to the `on_pressed` function for more than 2 seconds.
3. Observe the crash and the subsequent window offering to close or debug the program.

### Environment
- Operating System: Windows 10
- Python Version: python 3.10.6

I would appreciate any guidance on how to resolve this issue or advice on how to debug it using VSCode. I'm eager to give the script a try. 😄 

Thank you for any assistance!

**Comment by grassick** [comment]
Are you using the latest version? I fixed a bug today in Windows.

**Comment by Gerkinfeltser** [comment]
I was not! With your fixes it all works great. Thank you again!
